---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-docker
  name: hello-docker
  namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker
  template:
    metadata:
      labels:
        app: hello-docker
        namespace: challenge
    spec:
      containers:
      - image: harik8/hello-docker
        imagePullPolicy: Always
        name: hello-docker

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-docker
  name: hello-docker
spec:
  ports:
  - nodePort: 32001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-docker
  type: NodePort
